/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Wed May 23 11:02:03 GMT 2018
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkCounter_h__
#define __mkCounter_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCounter module */
class MOD_mkCounter : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_value;
 
 /* Constructor */
 public:
  MOD_mkCounter(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_load;
  tUInt8 PORT_EN_increment;
  tUInt8 PORT_load_newval;
  tUInt8 PORT_read;
  tUInt8 PORT_RDY_read;
  tUInt8 PORT_RDY_load;
  tUInt8 PORT_RDY_increment;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_increment;
  tUInt8 DEF_WILL_FIRE_load;
  tUInt8 DEF_CAN_FIRE_increment;
  tUInt8 DEF_CAN_FIRE_load;
  tUInt8 DEF_CAN_FIRE_read;
 
 /* Local definitions */
 private:
  tUInt8 DEF__read__h46;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt8 METH_read();
  tUInt8 METH_RDY_read();
  void METH_load(tUInt8 ARG_load_newval);
  tUInt8 METH_RDY_load();
  void METH_increment();
  tUInt8 METH_RDY_increment();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCounter &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCounter &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCounter &backing);
};

#endif /* ifndef __mkCounter_h__ */
